// <auto-generated />
using Beacon.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Beacon.StorageProviders.MsSqlServer.Migrations;

[DbContext(typeof(BeaconDbContext))]
[Migration("20230604193341_UpdateInviteTables")]
partial class UpdateInviteTables
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Beacon.API.Domain.Entities.Laboratory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("Laboratories");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.LaboratoryInvitation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("AcceptedById")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CreatedById")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedOn")
                    .HasColumnType("datetimeoffset");

                b.Property<double>("ExpireAfterDays")
                    .HasColumnType("float");

                b.Property<Guid>("LaboratoryId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("MembershipType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("NewMemberEmailAddress")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Id");

                b.HasIndex("AcceptedById");

                b.HasIndex("CreatedById");

                b.HasIndex("LaboratoryId");

                b.ToTable("LaboratoryInvitations");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.LaboratoryInvitationEmail", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("ExpiresOn")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("LaboratoryInvitationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("OperationId")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("SentOn")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("LaboratoryInvitationId");

                b.ToTable("LaboratoryInvitationEmails");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.LaboratoryMembership", b =>
            {
                b.Property<Guid>("LaboratoryId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("MemberId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("MembershipType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("LaboratoryId", "MemberId");

                b.HasIndex("MemberId");

                b.ToTable("LaboratoryMemberships");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EmailAddress")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("HashedPassword")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<byte[]>("HashedPasswordSalt")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.HasKey("Id");

                b.HasIndex("EmailAddress")
                    .IsUnique();

                b.ToTable("Users");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.LaboratoryInvitation", b =>
            {
                b.HasOne("Beacon.API.Domain.Entities.User", "AcceptedBy")
                    .WithMany()
                    .HasForeignKey("AcceptedById");

                b.HasOne("Beacon.API.Domain.Entities.User", "CreatedBy")
                    .WithMany()
                    .HasForeignKey("CreatedById")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Beacon.API.Domain.Entities.Laboratory", "Laboratory")
                    .WithMany()
                    .HasForeignKey("LaboratoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("AcceptedBy");

                b.Navigation("CreatedBy");

                b.Navigation("Laboratory");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.LaboratoryInvitationEmail", b =>
            {
                b.HasOne("Beacon.API.Domain.Entities.LaboratoryInvitation", "LaboratoryInvitation")
                    .WithMany("EmailInvitations")
                    .HasForeignKey("LaboratoryInvitationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("LaboratoryInvitation");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.LaboratoryMembership", b =>
            {
                b.HasOne("Beacon.API.Domain.Entities.Laboratory", "Laboratory")
                    .WithMany("Memberships")
                    .HasForeignKey("LaboratoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Beacon.API.Domain.Entities.User", "Member")
                    .WithMany("Memberships")
                    .HasForeignKey("MemberId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Laboratory");

                b.Navigation("Member");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.Laboratory", b =>
            {
                b.Navigation("Memberships");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.LaboratoryInvitation", b =>
            {
                b.Navigation("EmailInvitations");
            });

        modelBuilder.Entity("Beacon.API.Domain.Entities.User", b =>
            {
                b.Navigation("Memberships");
            });
#pragma warning restore 612, 618
    }
}
