name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/Server/Beacon.WebHost/Beacon.WebHost.csproj
    - name: Build
      run: dotnet build src/Server/Beacon.WebHost/Beacon.WebHost.csprojt --no-restore
    - name: Test
      run: dotnet test src/Server/Beacon.WebHost/Beacon.WebHost.csproj --no-build --verbosity normal

  build-blazor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/Client/Beacon.WebApp/Beacon.WebApp.csproj
    - name: Build
      run: dotnet build src/Client/Beacon.WebApp/Beacon.WebApp.csproj --no-restore
    - name: Test
      run: dotnet test src/Client/Beacon.WebApp/Beacon.WebApp.csproj --no-build --verbosity normal

  build-maui:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/Client/Beacon.DesktopApp/Beacon.DesktopApp.csproj
    - name: Build
      run: dotnet build src/Client/Beacon.DesktopApp/Beacon.DesktopApp.csproj --no-restore
#    - name: Test
#      run: dotnet test src/YourMauiProject --no-build --verbosity normal
